<?php
class trung_DtnOffice_block_adminhtml_department_Grid extends Mage_Adminhtml_Block_Widget_Grid
{
    public function _construct()
    {
        parent::_construct(); // TODO: Change the autogenerated stub
        $this->setId('id');
        $this->setDefaultSort('id');
        $this->setDefaultDir('ASC');
        $this->setSaveParametersInSession(true);
    }
    protected function _prepareCollection()
    {
        $collection = Mage::getModel('DtnOffice/department')->getCollection();
        $this->setCollection($collection);
        return parent::_prepareCollection(); // TODO: Change the autogenerated stub
    }
    protected function _prepareColumns()
    {
        $this->addColumn('id',array(
            'header'=> Mage::helper('DtnOffice')->__('id'),
            'align' =>'right',
            'width' => '50px',
            'index' => 'id',
        ));
        $this->addColumn('name',array(
            'header'=> Mage::helper('DtnOffice')->__('name'),
            'align' =>'left',
            'index' => 'name',
        ));
        return parent::_prepareColumns(); // TODO: Change the autogenerated stub
    }
    public function getRowUrl($row)
    {
        return '#';
    }
}
