<?php
class trung_DtnOffice_block_adminhtml_department_Grid extends Mage_Adminhtml_Block_Widget_Grid
{
    public function __construct()
    {
        parent::__construct(); // TODO: Change the autogenerated stub
        $this->setId('id');
        $this->setDefaultSort('id');
        $this->setDefaultDir('ASC');
        $this->setSaveParametersInSession(true);
    }
    protected function _prepareCollection()
    {
        $collection = Mage::getModel('DtnOffice/department')->getCollection();
        $this->setCollection($collection);
        return parent::_prepareCollection(); // TODO: Change the autogenerated stub
    }
    protected function _prepareColumns()
    {
        $this->addColumn('id',array(
            'header'=> 'id_department',
            'align' =>'center',
            'width' => '50px',
            'index' => 'id',
        ));
        $this->addColumn('name',array(
            'header'=> 'name',
            'align' =>'left',
            'index' => 'name',
        ));
        return parent::_prepareColumns(); // TODO: Change the autogenerated stub
    }
    public function getRowUrl($row)
    {
        return $this->getUrl('*/*/edit', array('id' => $row->getId()));
    }
}
