<?php

class onemoretime_two_block_twoblock extends Mage_Core_Block_Template
{
    public function _prepareLayout()
    {
        return parent::_prepareLayout(); // TODO: Change the autogenerated stub
    }
}
