<?php
echo "	<div class=\"slideshow_container\">
		<div class=\"myslide\">
			<img src=\"http://localhost:8686/slide/image1.jpg\">
		</div>
		<div class=\"myslide\">
			<img src=\"http://localhost:8686/slide/image2.jpg\">
		</div>
		<div class=\"myslide\">
			<img src=\"http://localhost:8686/slide/image3.jpg\">
		</div>
		<div style=\"text-align:center\">
			<span class=\"dot\" onclick=\"currentslide(0)\"></span> 
			<span class=\"dot\" onclick=\"currentslide(1)\"></span> 
			<span class=\"dot\" onclick=\"currentslide(2)\"></span> 	
		</div>
	</div>";

?>