<?php
$department = Mage::getModel("DtnOffice/department")->getCollection();
echo "<link rel='stylesheet' type='text/css' href='http://127.0.0.1:8686/css/bootstrap.min.css'>";
echo "<h5 class='ml-4'>Department Management</h5>";
echo "<table class='table table-stripe table-hover table-bordered col-6'>";
echo "<thead style='text-align: center' class='thead-dark'>";
echo "<th>ID</th>";
echo "<th>Department Name</th>";
echo "<th>Action</th>";
echo "</thead>";
echo "<tbody style='text-align: center'>";
foreach ($department as $value) {
    echo "<tr>";
    echo "<td>" . $value->id . "</td>";
    echo "<td>" . $value->name . "</td>";
    echo "<td><a href='#'>Edit</a> || <a href='#'>Delete</a></td>";
    echo "</tr>";
}
echo "</table>";
echo "<a href='http://127.0.0.1:8686/magento/dtn/department/create' class='btn btn-primary' style='margin-left: 100px'>Add Department</a>";
echo "</tbody>";
