<?php

class trung_DtnOffice_block_adminhtml_form_edit_form extends Mage_Adminhtml_Block_Widget_Form
{
     protected function _prepareForm()
     {
         return parent::_prepareForm(); // TODO: Change the autogenerated stub
         $form = new Varien_Data_Form(array(
             'id'=>'edit_form',
             'action'=>$this->getUrl('*/*/save',array('id'=>$this->getRequest()->getParams('id'))),
             'method'=>'post',
             'enctype'=>'multipart/form-data'
         ));
         $form->setUseContainer(true);
         $this->setForm($form);
         return parent::_prepareForm();
     }
}