<?php

class trung_DtnOffice_block_adminhtml_departmentblock extends Mage_Adminhtml_Block_Widget_Grid_Container
{
    public function __construct()
    {

        $this->_controller = 'adminhtml_department';
        $this->_blockGroup = 'DtnOffice';
        $this->_headerText ='Manage Department DTN';
        parent::__construct(); // TODO: Change the autogenerated stub
    }
}
