<?php

class trung_DtnOffice_block_adminhtml_employee_grid extends Mage_Adminhtml_Block_Widget_Grid
{
    public function __construct()
    {
        $this->setId('id');
        $this->setDefaultSort('id');
        $this->setDefaultDir('ASC');
        $this->setSaveParametersInSession('true');
        parent::__construct(); // TODO: Change the autogenerated stub
    }
    protected function _prepareCollection()
    {
        $collection = Mage::getModel('DtnOffice/employee')->getCollection();
        $this->setCollection($collection);
        return parent::_prepareCollection(); // TODO: Change the autogenerated stub
    }
    protected function _prepareColumns()
{

    $this->addColumn('id',array(
        'header'=>'id_employee',
        'index'=>'id',
        'type'=>'number'
    ));
    $this->addColumn('department_id',array(
        'header'=>'id_employee',
        'index'=>'department_id',
        'type'=>'number'
    ));
    $this->addColumn('email',array(
        'header'=>'Email',
        'align'=>'left',
        'index'=>'email',
        'width' => '100px'
    ));
    $this->addColumn('firstname',array(
        'header'=>'First Name',
        'align'=>'left',
        'index'=>'firstname',
        'width' => '50px'
    ));
    $this->addColumn('lastname',array(
        'header'=>'Last Name',
        'align'=>'left',
        'index'=>'lastname',
        'width' => '50px'
    ));
    $this->addColumn('workingyears',array(
        'header'=>'Working Years',
        'index'=>'working_years',
        'type'=>'number'
    ));
    $this->addColumn('dob',array(
        'header'=>'Date of Birth',
        'index'=>'dob',
        'type'=>'date'
    ));
    $currencyCode = Mage::app()->getStore()->getBaseCurrency()->getCode();
    $this->addColumn('salary',array(
        'header'=>'Salary',
        'index'=>'salary',
        'type'=> 'price',
        'currency_code' => $currencyCode
    ));
    $this->addColumn('note',array(
        'header'=>'Note',
        'index'=>'note',
    ));
    $this->addColumn('create_at',array(
        'header'=>'Create At',
        'index'=>'create_at',
        'type'=>'date'
    ));
    $this->addColumn('update_at',array(
        'header'=>'Update At',
        'index'=>'update_at',
        'type'=>'date'
    ));

    return parent::_prepareColumns(); // TODO: Change the autogenerated stub
}
    public function getRowUrl($row)
    {
        return $this->getUrl('*/*/edit', array('id' => $row->getId()));
    }
}