<?php
echo "
<div class=\"container\">
			<div id=\"myCarousel\" class=\"carousel slide col-5\" data-ride=\"carousel\" style='max-width: 700px'>
				<ol class=\"carousel-indicators\">
					<li data-target=\"#myCarousel\" data-slide-to=\"0\" class=\"active\"></li>
					<li data-target=\"#myCarousel\" data-slide-to=\"1\"></li>
					<li data-target=\"#myCarousel\" data-slide-to=\"2\"></li>
					<li data-target=\"#myCarousel\" data-slide-to=\"3\"></li>
				</ol>
				<div class=\"carousel-inner\">
					<div class=\"item active\">
						<img src=\"http://localhost:8686/slide/image1.jpg\" style=\"width: 100%\">
					</div>
					<div class=\"item\">
						<img src=\"http://localhost:8686/slide/image2.jpg\" style=\"width: 100%\">
					</div>
					<div class=\"item\">
						<img src=\"http://localhost:8686/slide/image3.jpg\" style=\"width: 100%\">
					</div>
					<div class=\"item\">
						<img src=\"http://localhost:8686/slide/image4.jpg\" style=\"width: 100%\">
					</div>
				</div>
				<a class=\"left carousel-control\" href=\"#myCarousel\" data-slide=\"prev\">
					<span class=\"glyphicon glyphicon-chevron-left\"></span>
					<span class=\"sr-only\">Previous</span>
				</a>
				<a class=\"right carousel-control\" href=\"#myCarousel\" data-slide=\"next\">
					<span class=\"glyphicon glyphicon-chevron-right\"></span>
					<span class=\"sr-only\">Next</span>
				</a>
				</div>
</div>
";
?>
