<?php

class trung_DtnOffice_model_department extends Mage_Core_Model_Abstract
{
        public function _construct()
        {
            parent::_construct(); // TODO: Change the autogenerated stub
            $this->_init('DtnOffice/department');
        }
}
