<?php
class onemoretime_four_block_fourblock extends Mage_Core_Block_Template {
    public function _prepareLayout()
    {
        return parent::_prepareLayout(); // TODO: Change the autogenerated stub
    }
}