<?php

class onemoretime_three_block_threeblock extends Mage_Core_Block_Template
{
    public function _prepareLayout()
    {
        return parent::_prepareLayout(); // TODO: Change the autogenerated stub
    }
}
