<?php

class trung_DtnOffice_model_mysql4_employee_collection extends Mage_Core_Model_Mysql4_Collection_Abstract
{
    public function _construct()
    {
        parent::_construct(); // TODO: Change the autogenerated stub
        $this->_init('DtnOffice/employee');
    }
}
